### ISSUE TITLE
`--force-metadata` issue

### ISSUE THREAD

**Issue by Lanchon** [7x11x13/scdl#4]
hi,

thanks so much for keeping up with soundcloud updates! right now this is the only tool i know of that works reliably, i really appreciate your work on this project.

right now `--force-metadata` overwrites tags (as it should) but *adds* a cover image. the result is that files with updated tags end up with multiple images for the front cover.

this is tested to happen at least when you want to retag from scaled-down cover images to original size images. i suppose this issue also happens when downloading the exact same image several times, but i have not tested that scenario.

many behaviors could be proposed to be done before retagging, such as clearing all images, or all front cover images, or the front cover image if it has exactly one, but the one i would ask you to consider is simply eliminating the ID3 tag set completely before retagging: this guarantees that the tags end up being exactly like they would on a freshly downloaded file.

thanks again!

**Comment by 7x11x13** [comment]
Thanks for reporting this, I implemented your suggestion in the latest commit
