### ISSUE TITLE
[RFE] use temp filename while downloading and tagging

### ISSUE THREAD

**Issue by Lanchon** [7x11x13/scdl#5]
hi,

if the download or tagging processes are interrupted or otherwise fail, a file is left on disk without any indication that it may not have the contents that the user asked for. i suggest doing all file processing (downloading, tagging...) using a filename with an added suffix (`.tmp`, `.$$$`, `.$`...) and only on successful termination of all tasks rename to remove the suffix.

IMHO a file with a suffix like `.$$$` could be safely overwritten always. before starting, a check could be done for the nonexistence of the file without the suffix if applicable. later on, while renaming, the file could be there even though it was not there before (this could happen for example if the user erroneously starts two download processes simultaneously for the same items) so it would be wise to set a behavior for this case.

additional rumblings:

while downloading `a.mp3` to `a.mp3.$temp` a file lock could be obtained, such as `a.mp3.$lock`. the idea would be to skip the download if the lock is held by another process (you know because you cannot open it exclusively; there are many examples of using files as locks online, better to take a look at standard practice). checking and acquiring the lock correctly is an atomic action, so you are guaranteed that at least one and only one process will have it. what is the use of this? a user could run several identical `scdl` tasks to download files concurrently.

the renaming and the locking would be always on, no matter the state of the `-c` flag.

**Comment by 7x11x13** [comment]
Hi, I'm now maintaining the original scdl repo, so if you want you can reopen this issue there. Thanks!
