### ISSUE TITLE
how to install this instead of flyringrub's scdl?

### ISSUE THREAD

**Issue by jamesryan-dev** [7x11x13/scdl#7]
python noob here 

getting the 403 error and would like to pivot to this? 

not really sure how to downlaod this ontop of my current scdl install

**Comment by 7x11x13** [comment]
Install the same way you installed the original scdl, just change the url from `https://github.com/flyingrub/scdl` to `https://github.com/7x11x13/scdl`

You may need to uninstall scdl first, I'm not sure!
